routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('article/{id}', 'ArticleController@show')->name('article');

Route::get('/', 'ArticleController@list')->name('articles');

Route::get('home/{id}', 'HomeController@show')->name('user');

/*AUTH ROUTES*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
/*ROUTE POUR AFFICHER LA LIST DES ARTICLES DANS HOME(USER SPACE)*/ 
Route::get('/home', 'HomeController@list')->name('articlelist');

Route::resource('crud', 'CrudController') ;

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title',
        'extract',
        'content',
        'image',
        'author_id'
      ];

    public function author()
    {
        return $this->belongsTo('App\User');
    }
}

app/Crud.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Crud extends Model
{
    protected $fillable = [
        'title',
        'extract',
        'content',
        'image',
        'author_id'
      ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
     'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
class ArticleController extends Controller
{
    
    public function show($id)
    {
        $article = Article::findOrFail($id);
        return view('article', ['article' => $article]);
    }


    public function list()
    {
        $articles = Article::All()
        ->sortByDesc("created_at");
        return view('articles', ['articles' => $articles]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use App\Crud;
use\App\Article;
use Illuminate\Http\Request;

class CrudController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
   
        $user = Auth::user();
        $articles = Article::where('author_id', $user->id)->get();
        return view('crud.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('crud.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'extract'=> 'required',
            'content' => 'required',
            'image' => 'required'
          ]);
          $crud = new Article([
            'title' => $request->get('title'),
            'extract'=> $request->get('extract'),
            'content' => $request->get('content'),
            'image'=> $request->get('image'),
            'author_id' => auth()->id()
          ]);
          $crud->save();
          return redirect('/crud')->with('success', 'Stock has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);

        return view('crud.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=>'required',
            'extract'=> 'required',
            'content' => 'required',
            'image' => 'required'
          ]);

          $crud = Article::find($id);
            $crud->title = $request->get('title');
            $crud->extract = $request->get('extract');
            $crud->content = $request->get('content');
            $crud->image = $request->get('image');
            $crud->author_id = auth()->id();

            $crud->save();
            return redirect('/crud')->with('success', 'Stock has been updated successfully');
          
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $crud = Article::find($id);
     $crud->delete();

     return redirect('/crud')->with('success', 'Stock has been deleted successfully');
          
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use Illuminate\Support\Facades\Auth;
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('/home');
    }
    public function list()
    {
        $user = Auth::user();
        $articles = Article::where('author_id', $user->id)->get();
        return view('home', ['articles' =>$articles]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
class UserController extends Controller
{
    public function show($id)
    {
        return view('/home', ['user' => User::findOrFail($id)]);
    }
}

resources/views/article.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <title>Document</title>
</head>
<body>

    <section class="container">
        <div class="card">
                <div class="card-body">
                    <div class="title-return-login">
                            <a href="/"><input type="button" class="btn-bluedark" value="RETURN"></a>
                            <h3 class="card-title text-center">{{$article->title}}</h3> 
                            @guest
                            @if (Route::has('register'))
                            <a href="{{ route('login') }}"><input type="button" class="btn-bluesky" value="LOGIN"></a>  
                            @endif
                          @else
                            <a href="{{ url('home') }}"><input type="button" class="btn-bluesky" value="PROFIL"></a> 
                    @endguest
                        </div>
                        <img class="card-img-top" src="{{$article->image}}" alt="">
                        <hr class="my-4">
                        <p class="card-text text-right">Published : {{$article->created_at}}</p>
                        <hr class="my-4">
                        <p class="card-text">{{$article->content}}</p>
                        <footer class="blockquote-footer text-right">
                            <cite>{{$article->author->username}}</cite>
                        </footer>
                </div>
            </div>    
    </section>
 
</body>
</html>

resources/views/articles.blade.php
@extends('layouts.app')
@section('content')
<!DOCTYPE html>
<html lang="en">
    <section class="container">
        <div class="card-columns">
                @foreach ( $articles as $article )
                <a href="{{route('article',['id' => $article->id])}}">
                    <div class="card">
                        <div class="card-body">
        
                                <h3 class="card-title text-center">{{$article->title}}</h3>
                                <img class="card-img-top" src="{{$article->image}}" alt="">
                                <p class="card-text text-justify">{{$article->extract}}</p>
                                <hr class="my-4">
                                <p class="card-text text-left">Published : {{$article->created_at}}</p>
                                <footer class="blockquote-footer">
                                    <cite>{{$article->author->username}}</cite>
                                </footer>
                        </div>
                    </div>    
                </a> 
                @endforeach       
        
        </div>
    </section>
@endsection

resources/views/crud/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="bg-card-create">

		
		@if ($errors->any())
			@foreach ($errors->all() as $error)
				<div class="alert alert-dismissible alert-danger">
				  <button type="button" class="close" data-dismiss="alert">×</button>
				  <strong>Oh snap!</strong>{{ $error }}
				</div>
			@endforeach
		@endif

		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title text-center">Add Article</h3>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" action="{{ route('crud.store') }}" method="POST">
					{{ csrf_field() }}
			  <fieldset>

			  	<div class="form-group">
			      <label for="title" class="col-md-2 control-label">Title</label>

			      <div class="col-md-10">
			        <input type="text" id="title" class="form-control" name="title" placeholder="Title">
			      </div>
			    </div>

			    <div class="form-group">
			      <label for="extract" class="col-md-2 control-label">Extract</label>

			      <div class="col-md-10">
			        <textarea id="extract" type="text" class="form-control" name="extract" placeholder="Extract"></textarea>
			      </div>
			    </div>

			    <div class="form-group">
                    <label for="content" class="col-md-2 control-label">Content</label>
  
                    <div class="col-md-10">
                      <textarea type="text" id="content" class="form-control" name="content" placeholder="Content"></textarea>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="image" class="col-md-2 control-label">Image</label>
  
                    <div class="col-md-10">
                      <input type="text" id="image" class="form-control" name="image" placeholder="Image">
                    </div>
                  </div>
                  
			    <div class="form-group">
			      <div class="col-md-10 col-md-offset-2">
			        <button type="submit" class="btn btn-primary">SUBMIT</button>
			      </div>
			    </div>
			  </fieldset>
			</form>
		 </div>
		</div>
	</div>
	</div>
@endsection

resources/views/crud/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="bg-card-create">
 
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form class="form-horizontal" method="post" action="{{ route('crud.update', $article->id) }}">
        @method('PATCH')
        @csrf
        <h3 class="text-center">EDIT</h3>
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Title</label>

            <div class="col-md-10">
            <input type="text" class="form-control" name="title" placeholder="Title" value="{{$article->title}}">
            </div>
          </div>

          <div class="form-group">
            <label for="extract" class="col-md-2 control-label">Extract</label>

            <div class="col-md-10">
              <textarea type="text" class="form-control" name="extract" placeholder="Extract">{{$article->extract}}</textarea>
            </div>
          </div>

          <div class="form-group">
              <label for="content" class="col-md-2 control-label">Content</label>

              <div class="col-md-10">
                <textarea type="text" class="form-control" name="content" placeholder="Content">{{$article->content}}</textarea>
              </div>
            </div>

            <div class="form-group">
              <label for="image" class="col-md-2 control-label">Image</label>

              <div class="col-md-10">
                <input type="text" class="form-control" name="image" placeholder="Image" value="{{$article->image}}">
              </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                  <button type="submit" class="btn btn-primary">UPDATE</button>
                </div>
              </div>
      </form>
  
  </div>

</div>
</div>
@endsection

resources/views/crud/index.blade.php
@extends('layouts.app')

@section('content')
<section class="container">
    <div class="table-responsive-sm table-responsive-md table-responsive-lg table-responsive-xl">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
              <td>ID</td>
              <td>Title</td>
              <td>Extract</td>
              <td>Date</td>
              <td colspan="2">Action</td>
            </tr>
        </thead>
        <tbody>
            @foreach($articles as $article)
            <tr>
                <td>{{$article->id}}</td>
                <td>{{$article->title}}</td>
                <td>{{$article->extract}}</td>
                <td>{{$article->created_at}}</td>
                <td class="info-posts"><a href="{{ route('crud.edit',$article->id)}}" class="btn-bluesky pencil"><i class="fas fa-pencil-alt"></i></a></td>
                <td class="info-posts">
                    <form action="{{ route('crud.destroy', $article->id)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="btn-danger1" type="submit"><i class="fas fa-times"></i></button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
      </table>    
    </div>
</section>
  @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
                @endif
                <h3 class="text-center">WELCOME {{ Auth::user()->username }}</h3>
                <p class="text-center">You are logged in!</p>

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
            </div>
        </div>
    </div>
</div>


<section class="container">
    <div class="card-columns">
            @foreach ( $articles as $article )
            
                <div class="card">
                    <div class="card-body">
    
                            <h3 class="card-title text-center">{{$article->title}}</h3>
                            <img class="card-img-top" src="{{$article->image}}" alt="">
                            <p class="card-text text-justify">{{$article->extract}}</p>
                            <hr class="my-4">
                            <p class="card-text text-left">Published : {{$article->created_at}}</p>
                            <footer class="blockquote-footer">
                                <cite>{{$article->author->username}}</cite>
                            </footer>
                            
                    </div>
                </div>    
            
            @endforeach       
    
    </div>
</section>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">    
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <p class="navbar-title">BLOG LARAVEL UI DESIGN</p>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}"><button class="btn-bluesky">{{ __('LOGIN') }}</button></a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}"><button class="btn-bluedark">{{ __('REGISTER') }}</button></a>
                                </li>
                            @endif
                        @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url('home') }}"><button class="btn-bluesky">{{ __('HOME') }}</button></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('crud.create') }}"><button class="btn-bluesky">{{ __('NEW POST') }}</button></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('crud.index') }}"><button class="btn-danger1">{{ __('MY POSTS') }}</button></a>
                        </li>
                    <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <button class="btn-bluesky">{{ Auth::user()->username }}<span class="caret"></span></button> 
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                    
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>